services:
  postgres_characters:
    container_name: 'postgres_characters'
    image: 'postgres:16.11-alpine3.23'
    env_file:
      - '.env'
    ports:
      - '5432:5432'
  valkey:
    container_name: 'valkey_game'
    image: 'valkey/valkey:9.0.1-alpine3.23'
    ports:
      - '6379:6379'
