services:
  postgres_game:
    container_name: 'postgres_game'
    image: 'postgres:16.11-alpine3.23'
    env_file:
      - '.env'
    ports:
      - '5432:5432'
  redis_game:
    container_name: 'redis_game'
    image: 'redis:6.2'
    ports:
      - '6379:6379'
